version: '3.8'

services:
  flask_app:
    image: 115_offdn_v3
    build: .
    volumes:
      - ./data:/app/data  # 호스트 시스템의 ./data 디렉토리를 컨테이너의 /app/data에 마운트. task_times.json파일 저장을 위함. 필수임.
    ports:
      - "5556:5000"
    environment:
      P115_COOKIE: "UID=...;CID=...;SEID=..." # 본인의 세 가지 쿠키값을 이어서 작성
      UID: "user account of 115 cloud" # 본인의 115 클라우드 계정번호를 넣음 또는 UID의 처음 9자리
      C_FolderId: "Default Download Folder ID" # 본인의 다운받을 기본 폴더 ID를 넣음.
      TZ: "Asia/Seoul"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  # 로그 파일당 최대 크기 (예: 10MB)
        max-file: "3"    # 로그 파일의 최대 개수
